mapfusion:
    solid:
        knn_feature_dim: 40
        max_range: 80
        num_sector: 60
        num_height: 16
        num_nearest_matches: 30
        num_match_candidates: 1
        fov_up: 15
        fov_down: -15
    interRobot:
        #topic
        solid_topic: "context"
        solid_frame: "base_link"
        local_topic: "lio_sam/mapping/cloud_info"

        # geode offroad
        # loop_threshold: 0.0008 # geode offroad
        # icp_threshold: 0.008 # geode offroad
        # # icp_threshold: 0.3 # geode offroad
        # pcm_start_threshold: 5   # 5 for best result, 2 for work in harsh environment
        # pcm_threshold: 20

        # geode tunnel
        # loop_threshold: 0.008 # geode tunnel
        # icp_threshold: 0.0003 # geode tunnel
        # pcm_start_threshold: 5   # 5 for best result, 2 for work in harsh environment
        # pcm_threshold: 20

        # moon (voxel_size: 2.0, max_range: 40)
        # loop_threshold: 0.01 # moon
        # icp_threshold: 2 # moon
        # pcm_start_threshold: 2   # 5 for best result, 2 for work in harsh environment
        # pcm_threshold: 20

        # graco (voxel_size: 0.75, max_range: 40)
        # loop_threshold: 0.5 # 
        # icp_threshold: 1.2
        # pcm_start_threshold: 2   # 5 for best result, 2 for work in harsh environment
        # pcm_threshold: 5

        # steam_legged (voxel_size: 0.75, max_range: 40)
        # loop_threshold: 0.5 # 
        # icp_threshold: 1.2
        # pcm_start_threshold: 2   # 5 for best result, 2 for work in harsh environment
        # pcm_threshold: 5

        # park (voxel_size: 2.0, max_range: 80)
        loop_threshold: 0.002 # 
        icp_threshold: 0.05
        pcm_start_threshold: 5   # 5 for best result, 2 for work in harsh environment
        pcm_threshold: 5

        # majang (voxel_size: 0.5, max_range: 80)
        # loop_threshold: 0.01 # 
        # icp_threshold: 0.001
        # pcm_start_threshold: 2   # 5 for best result, 2 for work in harsh environment
        # pcm_threshold: 10

        tmes_threshold: 100
        loop_frame_threshold: 10 #frames
        robot_initial: jackal0
        use_position_search: false #use position search may introduce more global loop closure, but spend more time for candidate checking